name: Release
on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      
      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu
      
      - name: Upload Windows Binary
        uses: actions/upload-artifact@v4
        with:
          name: clapscan-windows
          path: target/x86_64-pc-windows-gnu/release/clapscan.exe